### ISSUE TITLE
Issue about annotation with database failed

### ISSUE THREAD

**Issue by Echoring** [simon19891216/GFAP#1]
Thank you for developing such owesome tool for researchers in plant.

When I tried your tool on the website (http://43.139.112.84/go-kegg-pfam-index), I found that `2-annotation with database` seems works not properly. I used the example data provided, but only `swissprot` database successed. Selecting other 3 databases will return message `Opps!`.

I also tried the standalone version on our own computer as `python3 GFAP.py -o {outdir} -qn {cds.fasta} -qp {pep.fasta} -aws {species} -go -kegg -pfam -cpu {cpu} -awd nr -awd swissprot -mf -atf -agf`. All databases mentioned in README are downloaded and put in the `database` dir. However, no `nr` and `swissprot` annotation is reported. (only `GO_annotate`, `kegg_annotate`, `pfam_annotate`, `GF_result`, and a blank `swissprotf_result`)

(By the way, the requirement `svglab==1.4.1` is not fount in pip, and the program report that it cannot found `svglib` module. Is this a typo?)

Looking forward to your reply.

**Comment by simon19891216** [comment]
Thank you for your interest in GFAP. The issues with the Linux version are primarily caused by different versions. I have updated the files, so please download it and try again. Based on your description, I have rechecked these features, and from the results, it seems that there are no issues. The steps I take are as follows: click the “using example data” button to input data, select “protein” as the "sequence type", choose “GO” as the "annotation type", select “plant-special database” as the database, and finally, click the “annotate” button for running this function. Please try again! If there are still any usage-related issues, feel free to contact me by email or github.

**Comment by simon19891216** [comment]
Furthermore, the specific information about Linux command line can be found on our GitHub website. You can download it and refer to it for usage.

**Comment by Echoring** [comment]
Thank you for your help. I tried again the web tool, and find that check annotation type `GO` and `protein domains` can successfully annotate, but `KEGG` return `Opps!`.

Edit: Seems the refering GitHub website about Linux command line is not given anywhere. Can you paste it here?

**Comment by simon19891216** [comment]
This is a difficult question to understand. I logged into our server and checked the output logs. I found that the KEGG file has been generated and there are no error messages (as following pricture).
![Snipaste_2023-07-18_18-20-43](https://github.com/simon19891216/GFAP/assets/40338037/97042e01-2288-4e5f-ae1e-d1281cec0121)
I speculate that the lack of kegg results being returned to you might be due to a slow internet connection. So, I suggest you try again, this time only using one type of functional annotation with KEGG. I apologize for the inconvenience. It’s my mistake that the usage instructions for the Linux part of GFAP are missing. Please be patient, I will upload the usage instructions to GitHub within one day. I apologize once again.

**Comment by simon19891216** [comment]
the manual of GFAP has been uploaded into this account. as
![image](https://github.com/simon19891216/GFAP/assets/40338037/8b73879f-46a2-4b47-a1c3-df7b194da5f9)

**Comment by Echoring** [comment]
I've tried the updated linux version. A new module `chardet` is imported and missing in `requirements.txt`.
After solving this I gain satisfactory result.
The web tool's KEGG annotation seems still not work for me, but anyway, the standalone version work.
Thanks for your help again!
