### ISSUE TITLE
GFAP fails silently

### ISSUE THREAD

**Issue by katieemelianova** [simon19891216/GFAP#2]
Hi there,

I'm attempting to run GFAP using a few sequences at first, and all things that I attempt fail silently:
e.g:
```
python3 GFAP.py -go -qn test.fasta -o test_out 
```
I first needed to install a few python packages before it ran, but once I installed them there are no error messages, regardless of whether I run GFAP.py or GFAP-linux.py. I did not compile anything before I ran it, and I couldn't seem to find any installation instructions, so I assume I have not skipped any steps since cloning the code from gitghub?

Could you please advise what I can do to debug?

Best,

Katie

**Comment by simon19891216** [comment]
Thank you for your question. There seems to be an issue with the command you are using. Before using GFAP, you need to download the database.Could you please provide me with your email address so that I can send you the operational instructions?



At 2024-07-11 20:00:47, "katieemelianova" ***@***.***> wrote:

Hi there,

I'm attempting to run GFAP using a few sequences at first, and all things that I attempt fail silently:
e.g:

python3 GFAP.py -go -qn test.fasta -o test_out 


I first needed to install a few python packages before it ran, but once I installed them there are no error messages, regardless of whether I run GFAP.py or GFAP-linux.py. I did not compile anything before I ran it, and I couldn't seem to find any installation instructions, so I assume I have not skipped any steps since cloning the code from gitghub?

Could you please advise what I can do to debug?

Best,

Katie

**Comment by katieemelianova** [comment]
Hi there,

Thanks for your reply, please could you send the documentation to katie_emelianova@hotmail.com

Best,

Katie

**Comment by katieemelianova** [comment]
Thanks for your online help with this, I have dowloaded the databases now from the FTP link specified in the documentation.

Best,

Katie
